function [static_mask, activity_map] = compute_static_mask( ...
        tif_folder, activity_threshold, binarize_thr, dilation_radius)
% COMPUTE_STATIC_MASK  Detect static reflection pixels in an event sequence.
%   Classifies pixels as static if their activity fraction across all frames
%   meets or exceeds activity_threshold. The mask is morphologically dilated
%   to cover reflection drift caused by mechanical vibration.
%
% INPUTS:
%   tif_folder          Path to the folder containing the .tif frame
%                       sequence generated by the event camera.
%
%   activity_threshold  Fraction of frames a pixel must be active to be
%                       flagged [0,1]. Default: 0.20.
%
%   binarize_thr        Intensity threshold for active-pixel detection [0,255].
%                       Default: 10.
%
%   dilation_radius     Dilation disc radius [px]. Default: 5.
%
% OUTPUTS:
%   static_mask         Logical matrix (H x W). true = pixel flagged as a
%                       static reflection; must be excluded before
%                       correlation.
%
%   activity_map        Double matrix (H x W) with the per-pixel fraction
%                       of frames in which each pixel was active, normalised
%                       to [0, 1]. Use this to calibrate activity_threshold
%                       before applying the definitive mask.
%
%   Saves activity_map.png and static_mask.png in tif_folder for inspection.


    % Default arguments
    if nargin < 2 || isempty(activity_threshold), activity_threshold = 0.20; end
    if nargin < 3 || isempty(binarize_thr),       binarize_thr       = 10;   end
    if nargin < 4 || isempty(dilation_radius),    dilation_radius    = 5;    end

    % Load frame sequence
    files = dir(fullfile(tif_folder, '*.tif'));
    if isempty(files)
        error('compute_static_mask: no .tif files found in: %s', tif_folder);
    end
    N = numel(files);
    fprintf('compute_static_mask: processing %d frames...\n', N);

    img0 = imread(fullfile(files(1).folder, files(1).name));
    if size(img0, 3) > 1, img0 = rgb2gray(img0); end   % handle RGB if needed
    [H, W] = size(img0);

    % --- Accumulate active-pixel counts ---
    accumulator = zeros(H, W, 'double');

    for k = 1:N
        img = imread(fullfile(files(k).folder, files(k).name));
        if size(img, 3) > 1, img = rgb2gray(img); end
        accumulator = accumulator + double(img > binarize_thr);
    end

    % Normalised activity map
    activity_map = accumulator / N;

    % Initial static pixel mask
    static_mask = activity_map >= activity_threshold;

    % --- Morphological dilation: cover vibration-induced halo ---
    if dilation_radius > 0
        se          = strel('disk', dilation_radius);
        static_mask = imdilate(static_mask, se);
        fprintf('compute_static_mask: morphological dilation applied (radius = %d px).\n', ...
                dilation_radius);
    end

    % Diagnostic report
    n_static  = sum(static_mask(:));
    pct_static = 100 * n_static / (H * W);
    fprintf('compute_static_mask: %d pixels masked (%.2f%% of sensor area).\n', ...
            n_static, pct_static);

    % Activity map image: scaled to [0, 255] for easy visual inspection.
    % Bright areas indicate high persistent activity (reflection candidates).
    imwrite(uint8(activity_map * 255), fullfile(tif_folder, 'activity_map.png'));

    % Static mask image: white = masked (excluded from correlation).
    % Inspect to confirm the mask covers the reflection without invading
    % the flow region of interest.
    imwrite(uint8(static_mask * 255), fullfile(tif_folder, 'static_mask.png'));

    fprintf('compute_static_mask: diagnostic images saved in %s\n', tif_folder);
end